<h1 class="text-3xl font-bold text-blue-600">Welcome to my Portfolio!</h1>
<br/>
<p>Argumenten emot uppfattningen att brevet skrivits av Jakob inbegriper att det är skrivet på driven grekiska,[1] något många menar att en enkel och outbildad palestinier med arameiska som modersmål knappast vore i stånd till, om än vissa anser det inte vara uteslutet.[35] Det faktum att grekiskan förekom i Palestina innebär inte, enligt Werner Kümmel, att en arameisktalande jude i vanliga fall kunde skriva på flytande grekiska.[36] Författaren är dessutom väl förtrogen med Septuaginta, den grekiska översättningen av Gamla testamentet, och de bibelcitat som förekommer i brevet är hämtade därifrån.[37] Det finns heller inga tydliga tecken på att det skulle vara en översättning gjord från en arameisk förlaga.[38] Och enligt Bart D. Ehrman var Jakob en arameisktalande bonde från Galileen som med nästan absolut säkerhet inte ens kunde läsa och skriva, än mindre författa ett verk på flytande grekiska.[37] Ehrman menar att den som skrev detta brev var en mycket bildad person med grekiska som modersmål, som skrev en klar och korrekt koinegrekiska och som hade förmågan att bruka en mängd retoriska tekniker som var vanliga inom grekisk-romersk moralfilosofi.[39] Av dessa anledningar menar han att det är näst intill omöjligt att föreställa sig att Jakobsbrevet har skrivits av Jakob, en outbildad bonde från landsbygdens Nasaret.[40] (Vad gäller svårigheten för en outbildad arbetare, som en jordbrukare eller fiskare, från den galileiska landsbygden att kunna författa ett brev på grekiska, se Andra Petrusbrevet, läs- och skrivkunnigheten i Galileen.)
<br/>
<br/>
En annan invändning mot att Jakob skulle vara författaren, är att det ingenstans i brevet framkommer att författaren har någon egen relation till Jesus.[35] Jesus nämns för övrigt vid namn bara två gånger i brevet (Jak 1:1; 2:1) och då endast som herren Jesus Kristus. Inget sägs heller om att hans död och uppståndelse skulle utgöra grund för frälsningen.[41][42] Vidare var skriften omstridd i den äldsta kyrkan och dess accepterande i kanon tog lång tid. Det finns inga säkra spår efter att någon använt sig av Jakobsbrevet före 200-talet,[43][44] men det finns tecken på att Irenaeus var bekant med det cirka år 180.[45] Det saknas i Muratoriekanon,[46] Tertullianus nämner det inte,[43] och det citerades som auktoritativ skrift först av Origenes i mitten av 200-talet.[47] På 300-talet skriver Eusebios av Caesarea att brevet ofta har ansetts vara oäkta och att inte många gamla författare har nämnt det.[48][43][46] Flera forskare har tolkat brevets andra kapitel, verserna 2:14–26, som ett angrepp på Paulus,[49][50] varför i så fall brevet måste ha skrivits efter det att Paulus brev hade samlats och börjat cirkulera, något som skedde senare än år 62 när Jakob antas ha dött. Och man har undrat hur Jakob, om han verkligen är författaren, kan ha undgått att ta upp frågan om konvertiternas förhållande till judiska lagar och riter.[38] I alla källor sägs Jakob värna den judiska lagen och såväl kulturellt som kultiskt hålla fast vid den judiska identiteten. Men i Jakobsbrevet finns inget rituellt eller kultiskt, inget om renhetslagar, det judiska templet, tillåten mat, sabbaten, högtidsdagar, omskärelse, Israel eller något annat som hör till den judiska identiteten.[51] I stället handlar det om kärleksbudet att Du skall älska din nästa som dig själv (Jak 2:8) eller om budorden (Jak 2:10–12).[52] Det förekommer heller inga antydningar i brevet om schismer mellan judiska och icke-judiska kristna, och soteriologin, frälsningsläran, i brevet riktar sig till de hednakristna och avviker därmed kraftigt från den orientering mot de judekristna som Jakob representerar enligt det Paulus skriver i Galaterbrevet.[53][54]
<br/>
<br/>
Andra tecken på att brevet inte är från den närmaste tiden efter Jesu död, och därmed heller inte skrivet av Jakob, är dess beskrivning av förhållanden som antas ha rått vid en senare tid. Det handlar om upplevda bekymmer över att det finns alltför många rika i församlingarna (Jak 2:1–6; 5:1–6), att folk verkar vara otåliga över att Jesus ännu inte kommit (grekiska: παρουσία, parousia) (Jak 5:8–9) och att ”de äldste” (grekiska: πρεσβύτερος, presbyteros) förefaller leda församlingarna (Jak 5:14). Detta är omständigheter som alla påminner mer om de förhållanden som rådde senare. Mot slutet av nollhundratalet anslöt allt fler till den kristna rörelsen och då också många fler rika, varför sociala konflikter uppstod i församlingarna. Liknande förhållanden står att finna främst i Lukasevangeliet, Uppenbarelseboken och de pseudopaulinska Pastoralbreven, vilka anses ha skrivits vid en senare tid än den när Paulus skrev sina brev.[54][55]</p>
